groups:
  default:
  - geoconverter
containers:
  geoconverter: &cref
    build:
      context: ..
      file: Dockerfile
    image: geometalab/geoconverter
    run: &crefrun
      detach: false
      env:
      - VIRTUAL_HOST=$VIRTUAL_HOST
#      - VIRTUAL_PORT=$VIRTUAL_PORT
      - CERT_NAME=$CERT_NAME
#      - LETSENCRYPT_HOST=$LETSENCRYPT_HOST
#      - LETSENCRYPT_EMAIL=$LETSENCRYPT_EMAIL
      - DJANGO_ADMIN_USER=$DJANGO_ADMIN_USER
      - DJANGO_ADMIN_EMAIL=$DJANGO_ADMIN_EMAIL
      - DJANGO_ADMIN_PASS=$DJANGO_ADMIN_PASS
      - DJANGO_ADMINS=$DJANGO_ADMINS
      - DJANGO_ALLOWED_HOSTS=$DJANGO_ALLOWED_HOSTS
#      - DJANGO_CACHE_DEFAULT_URL=$DJANGO_CACHE_DEFAULT_URL
#      - DJANGO_DB_CONVERTER_URL=$DJANGO_DB_CONVERTER_URL
#      - DJANGO_DB_DEFAULT_URL=$DJANGO_DB_DEFAULT_URL
#      - DJANGO_DB_JOBS_URL=$DJANGO_DB_JOBS_URL
#      - DJANGO_DB_LOGS_URL=$DJANGO_DB_LOGS_URL
#      - DJANGO_DB_SESSIONS_URL=$DJANGO_DB_SESSIONS_URL
      - DJANGO_DEBUG=$DJANGO_DEBUG
      - DJANGO_DEFAULT_FROM_EMAIL=$DJANGO_DEFAULT_FROM_EMAIL
      - DJANGO_EMAIL_BACKEND=$DJANGO_EMAIL_BACKEND
      - DJANGO_EMAIL_FILE_PATH=$DJANGO_EMAIL_FILE_PATH
      - DJANGO_EMAIL_HOST=$DJANGO_EMAIL_HOST
      - DJANGO_EMAIL_HOST_PASSWORD=$DJANGO_EMAIL_HOST_PASSWORD
      - DJANGO_EMAIL_HOST_USER=$DJANGO_EMAIL_HOST_USER
      - DJANGO_EMAIL_PORT=$DJANGO_EMAIL_PORT
      - DJANGO_EMAIL_SUBJECT_PREFIX=$DJANGO_EMAIL_SUBJECT_PREFIX
      - DJANGO_EMAIL_TIMEOUT=$DJANGO_EMAIL_TIMEOUT
      - DJANGO_EMAIL_USE_TLS=$DJANGO_EMAIL_USE_TLS
      - DJANGO_EMAIL_USE_SSL=$DJANGO_EMAIL_USE_SSL
      - DJANGO_ENV_FILE=$DJANGO_ENV_FILE
#      - DJANGO_MEDIA_ROOT=$DJANGO_MEDIA_ROOT
#      - DJANGO_PRIVATE_MEDIA_ROOT=$DJANGO_PRIVATE_MEDIA_ROOT
      - DJANGO_SECRET_KEY=$DJANGO_SECRET_KEY
      - DJANGO_SERVER_EMAIL=$DJANGO_SERVER_EMAIL
#      - DJANGO_STATICFILES_DIRS=$DJANGO_STATICFILES_DIRS
#      - DJANGO_STATIC_ROOT=$DJANGO_STATIC_ROOT
#      - DJANGO_STATIC_URL=$DJANGO_STATIC_URL
#      - DJANGO_X_FRAME_OPTIONS=$DJANGO_X_FRAME_OPTIONS
      stop-signal: SIGTERM
      interactive: false
      tty: false
      volume:
      - geoconverter-data_data:/data:rw
      - geoconverter-data_output:/output:rw
    exec:
      interactive: true
      tty: true
  cshell: { <<: *cref, run: { <<: *crefrun, detach: false, entrypoint: /bin/bash, cmd, tty: true, interactive: true } }
hooks:
volumes:
  geoconverter-data_data:
  geoconverter-data_output:
